name: JAL2pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - polars
  - opencv
  - pillow
  - h5py
  - pyarrow
  - astropy
  - scikit-learn
  - scikit-image
  - statsmodels
  - bottleneck
  - hdbscan
  - umap-learn
  - resampy
  - tqdm
  - numba
  - llvmlite
  - pytorch
  - autograd
  - nptdms
  - pyyaml
  - ffmpeg
  - ipykernel
  - tk
  - pip:
      - loguru
      - dill
      - ephysiopy
