# TODO the tracking data is not being pickled. tracking_data needs to be pickled to use for the analysis. 

# Custom Libaries
from behave_analysis.track.dlcHelp import DLC
from behave_analysis.track.kalmanFilter import kalmann

# OS Libaries
from loguru import logger
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import dill as pickle

class Track(DLC):
    """
    A tracking class that checks if DLC has been run yet on the session upon 
    initialization. If not, it runs DLC. Then it processes the tracking data by removing
    any bad tracking data, correcting for fisheye distortion, and computing metrics
    for the tracking. The prior before metric computation step is to apply a kalman filter to the tracking data. And 
    then this is saved into a dictionary.
    
    For each body part tracked by DLC, the keys will be: 
    + dict_keys(['x', 'y', 'likelihood', 'xVelocity', 'yVelocity', 'xAccel', 'yAccel'])
    + Such that it is a dictionary of dictionaries.

    Args:
        DLC (object): A class to handle DLC related data and functions.
    """
    def __init__(self, settings, session):
        self.settings = settings
        self.run_deeplabcut_tracking(session)
        self.process_tracking_data(session)
    
    def process_tracking_data(self, session):
        """Check if the tracking data has been processed before, if not run this function.
        There is a flag in the settings_track option to skip or redo the processing step if needed.
        If set to False (not False = True) it will skip processing if it has already been done. 

        Args:
            session (object): session dataclass
        """
        
        # Check if processing has been done before
        self.processingExists = os.path.isfile(os.path.join(session.file_path, "fully_processed_tracking_data.pickle"))

        # If processing has been done before and you don't want to redo it then log it
        if self.processingExists and not self.settings.redo_processing_step: 
            logger.info(f"Tracking data already filtered and registered for session: {session.number} - {session.name}")
        
        # If not regristration details have been found then log it and kill session
        elif isinstance(session.video.registration_transform, type(None)):
            logger.error(f"Registration details not found; and subsequently the tracking can't be processed for session: {session.number} - {session.name}")
            assert session.video.registration_transform, "This should exist"
            
        # If processing has not been done before or you want to redo it then run it
        else:
            if self.settings.redo_processing_step:
                logger.info("You have choosen to redo processing step")
                
            logger.info(f"Processing tracking data for session: {session.number} - {session.name}")
            
            # Processing tracking data
            self.create_dlc_tracking_array(session)
            self.remove_bad_tracking_data(session)
            self.correct_and_register(session)
            
            # New linear dynamical system logic
            self.apply_kalman(session)
            self.save_kalman(self.lds_tracking_data, session) # Linear dynamical system tracking data generated by kalman filter
            
            # Metric computation
            self.compute_metrics(session)
            self.save_tracking_data(session)
            # self.compute_average_body_part_with_kalman()
            # self.plot_tracking()
            
# -----REGISTERING CAMERA FUNCS--------------------------------------------------------------

    def correct_and_register(self, session):
        self.fisheye_correct_tracking_data(session)
        self.register_tracking_data(session)

    def fisheye_correct_tracking_data(self, session):
        if self.settings.inverse_fisheye_correction_file:
            inverse_fisheye_map = np.load(self.settings.inverse_fisheye_correction_file)
            self.fisheye_corrected_tracking_data_array = \
                    inverse_fisheye_map[self.tracking_data_array[:,:,1].astype(np.uint16) + session.video.y_offset,     \
                                        self.tracking_data_array[:,:,0].astype(np.uint16) + session.video.x_offset, :2] \
                                            - np.array([session.video.x_offset, session.video.y_offset])
        else: 
            self.fisheye_corrected_tracking_data_array = self.tracking_data_array[:,:,:2]

    def register_tracking_data(self, session):
        """
            Register the tracking data to the video. This is done by applying the registration transform. NOTE, that in this
            function the tracking data now takes the form of registered_tracking_data_before_kalman. 
        """
        
        self.registered_tracking_data_before_kalman = {}
        
        for i, bodypart in enumerate(self.tracking_data_body_parts['bodyparts']):
            if 'affine' in session.video.registration_type:
                registration_transform = np.append(session.video.registration_transform, np.zeros((1, 3)), 0)
                self.registered_tracking_data_before_kalman[bodypart] = cv2.transform(np.array([self.fisheye_corrected_tracking_data_array[:, i, 0:2].astype(np.float32)]), registration_transform)[0]
            if 'homography' in session.video.registration_type:
                registration_transform = session.video.registration_transform
                self.registered_tracking_data_before_kalman[bodypart] = cv2.perspectiveTransform(np.array([self.fisheye_corrected_tracking_data_array[:, i, 0:2].astype(np.float32)]), registration_transform)[0]
          
            self.registered_tracking_data_before_kalman[bodypart][self.registered_tracking_data_before_kalman[bodypart]<0] = 0
              
# -----KALMAN FILTER FUNCS--------------------------------------------------------------

    def apply_kalman(self, session) -> None:
        """
           The kalman filter is a recursive algorithm that estimates the state of a system using a sequence of measurements.
           This function requires the tracking data to be in the form of a numpy array with the following dimensions:
            + (2, frames)
           The algorithm works on a single body part and thus needs to be called in a recursive manner.
        """
        if os.path.isfile(os.path.join(session.file_path, "kalman_tracking_data.pickle")):
            logger.warning("Kalman tracking exists but you've chosen to redo processing")
            
            # Load the kalman tracking data to speed up development but NOTE remove this code
            
            path = os.path.join(session.file_path, "kalman_tracking_data.pickle")
            with open(path, 'rb') as f:
                # deserialize the data and load it into a Python object
                self.lds_tracking_data = pickle.load(f)
            
            return None
            
        
        logger.info("Creating new kalman tracking data.")
        
        ldsResults = {}
        
        for i, bodypart in enumerate(self.tracking_data_body_parts['bodyparts']):
            x = self.registered_tracking_data_before_kalman[bodypart][:, 0]
            y = self.registered_tracking_data_before_kalman[bodypart][:, 1]
            xy = np.vstack((x, y))
            
            results = kalmann(xy)
            ldsResults[bodypart] = {"x": results["x"], 
                                    "y": results["y"], 
                                    "likelihood": self.tracking_data_array[:, i, 2],
                                    "xVelocity": results["xVelocity"],
                                    "yVelocity": results["yVelocity"],
                                    "xAccel": results["xAccel"],
                                    "yAccel": results["yAccel"],
                                    }
            
        self.lds_tracking_data = ldsResults
        self.save_kalman(self.lds_tracking_data, session)
        return None
        
    def save_kalman(self, dictionary, session) -> None:
        """
        Save the kalman tracking dictionary to a pickle file contained within the session folder. 
        """
        savePath = os.path.join(session.file_path, "kalman_tracking_data.pickle")
        with open(savePath, "wb") as dill_file: 
            pickle.dump(dictionary, dill_file)

# -----METRIC COMPUTATION FUNCS--------------------------------------------------------------

    def compute_metrics(self, session):
        # Leaving in session as you in this reference location speed computation
        regionsOI = self.map_regions_of_interest()
        self.compute_avg_region_location(regionsOI)
        self.compute_new_angles()
        self.compute_new_average_speed()
        self.region_tracking_data['bodyparts'] = self.tracking_data_body_parts['bodyparts'] # Needed for visualization
        # self.compute_speed(session)
        # self.compute_speed(session, reference_location=session.video.shelter_location, reference_name=' rel. to shelter')
        
    def map_regions_of_interest(self) -> dict:
        """
        Map regions of body to individual body parts. This function needs to be changed if the list of 
        body parts change in deep lab cut. These are hardcoded regions of interest that need to be mannually mapped to the body parts.
        """
        regionsOI = {
                     'avg_loc': self.tracking_data_body_parts['bodyparts'],
                     'neck_loc': ['left_ear', 'upper_back', 'right_ear'],
                     'upper_body_loc': ['left_shoulder', 'upper_back', 'right_shoulder'],
                     'lower_body_loc': ['left_hind_limb', 'lower_back', 'right_hind_limb', 'tail_base'],
                     'head_loc': ['left_ear', 'right_ear'],
                     'body_loc': ['upper_back', 'lower_back']
                     }
        return regionsOI
            
    def compute_avg_region_location(self, regionsOI):
        """
        Compute the average location of the body parts in a region of interest into a dictionary called 
        region tracking data. This is done by taking the mean of the x and y coordinates of the body parts"
        """
        self.region_tracking_data = {}
        
        for region in regionsOI.keys():
            x = np.mean([self.lds_tracking_data[bodypart]['x'] for bodypart in regionsOI[region]], axis=0)
            y = np.mean([self.lds_tracking_data[bodypart]['y'] for bodypart in regionsOI[region]], axis=0)
            self.region_tracking_data[region] = np.array([[x, y] for x, y in zip(x, y)])
        
        logger.info("Body points averaged and their positions have been averaged and mapped to regions of interest.")       
    
    def compute_new_angles(self):
        """
        A function to compute the angles of the body parts.
        
        NOTE: Removed neck_dir but might need to add it back in.
        """
        
        # print(self.region_tracking_data['head_loc'].shape)
        
        # print(self.region_tracking_data['head_loc'][:100])
        
        hedDelta_x = self.region_tracking_data['head_loc'][:, 0] - self.region_tracking_data['upper_body_loc'][:, 0]
        hedDelta_y = self.region_tracking_data['head_loc'][:, 1] - self.region_tracking_data['upper_body_loc'][:, 1]
        self.region_tracking_data['hdir'] = np.arctan2(hedDelta_y, hedDelta_x) # Radians
        
        bodDelta_x = self.region_tracking_data['upper_body_loc'][:, 0] - self.region_tracking_data['lower_body_loc'][:, 0]
        bodDelta_y = self.region_tracking_data['upper_body_loc'][:, 1] - self.region_tracking_data['lower_body_loc'][:, 1]
        self.region_tracking_data['body_dir'] = np.arctan2(bodDelta_y, bodDelta_x) # Radians
        
       
        
        
        
        # bodangles = np.arccos(boddelta_x/np.sqrt(np.power(boddelta_x,2)+np.power(boddelta_y,2)))
        
        # self.region_tracking_data['hdir'] = np.rad2deg(bodangles)
        # opp = boddelta_y/np.sqrt(np.power(boddelta_x,2)+np.power(boddelta_y,2))
        # self.region_tracking_data['hdir'][opp<0] = (2*np.pi) - self.region_tracking_data['hdir'][opp<0]
        
        # print(self.region_tracking_data['hdir'][:100
        #                                         ])
        
        # self.region_tracking_data['body_dir'] = np.angle((self.region_tracking_data['upper_body_loc'][:, 0] - self.region_tracking_data['lower_body_loc'][:, 0]) \
        #                                                   + (-self.region_tracking_data['upper_body_loc'][:, 1] + self.region_tracking_data['lower_body_loc'][:, 1]) * 1j, 
        #                                                   deg=True)
        
        # self.region_tracking_data['hdir'] = np.angle((self.region_tracking_data['head_loc'][:, 0] - self.region_tracking_data['upper_body_loc'][:, 0]) \
        #                                              + (-self.region_tracking_data['head_loc'][:, 1] + self.region_tracking_data['upper_body_loc'][:, 1]) * 1j, 
        #                                              deg=True)
        
        logger.info("Head direction and body direction computed")
        
    
    
    def compute_new_average_speed(self):
        """
        Calculate the velocity of the mouse. The velocity is the average of the x and y velocities of the body parts.
        It can be negative. How so? In reference to what?
        """
        avgX = np.mean([self.lds_tracking_data[bodypart]['xVelocity'] for bodypart in self.tracking_data_body_parts['bodyparts']], axis=0)
        avgY = np.mean([self.lds_tracking_data[bodypart]['yVelocity'] for bodypart in self.tracking_data_body_parts['bodyparts']], axis=0)
        self.region_tracking_data['avg_Velocity'] = np.array([[x, y] for x, y in zip(avgX, avgY)])
    
    # There seems to be a second component to the old function for the speed calculatuion that is not being used. Leaving as don't understand what it is doing yet.
    # What is the refernece component? 
    
    def compute_speed(self, session, reference_location: tuple = None, reference_name: str=''):
        if not reference_location:
            speed_x_and_y_pixel_per_frame = np.diff(self.tracking_data['avg_loc'], axis=0) 
            speed_pixel_per_frame = (speed_x_and_y_pixel_per_frame[:, 0]**2 + speed_x_and_y_pixel_per_frame[:, 1]**2)**.5
        else:
            distance_from_reference_location = ((self.tracking_data['avg_loc'][:,0] - reference_location[0])**2 + \
                                                (self.tracking_data['avg_loc'][:,1] - reference_location[1])**2)**.5
            self.tracking_data['distance' + reference_name] = distance_from_reference_location
            speed_pixel_per_frame = -np.diff(distance_from_reference_location)
        speed_cm_per_sec = speed_pixel_per_frame * session.video.fps / session.video.pixels_per_cm
        smoothed_speed_cm_per_sec = gaussian_filter1d(speed_cm_per_sec, sigma=session.video.fps/10)
        self.tracking_data['speed' + reference_name] = smoothed_speed_cm_per_sec

# --------UTILITY FUNCS---------------------------------------------------------------------

    def save_tracking_data(self, session) -> None:
        """
        A function to save the tracking data pickled.
        """
        savePath = os.path.join(session.file_path, "fully_processed_tracking_data.pickle")
        with open(savePath, "wb") as dill_file: 
            pickle.dump(self.region_tracking_data, dill_file)
        
        logger.info("Tracking data saved to {}".format(savePath))

# -----METRIC PLOTTING FUNCS--------------------------------------------------------------

    def plot_tracking(self):
        if self.settings.display_tracking_output:
            for axis in [0,1]:
                plt.figure()
                plt.title('Example of 10,000 time-points of tracking data - axis {}'.format(axis))
                for bodypart in self.tracking_data['bodyparts']:
                    plt.plot(self.tracking_data[bodypart][10000:20000, axis])
                plt.legend(self.tracking_data['bodyparts'])
            plt.figure(figsize=(12,6))
            plt.title('Histogram of confidence in tracking data')
            plt.hist(self.tracking_data_array[:,:,2], 20, density=True)
            plt.show()
    